validate:
  stage: test
  script:
    - grep -i '^*\.jpg' .gitattributes    # Track *.jpg
    - grep -i '^*\.png' .gitattributes    # Track *.png
    - grep -i '^*\.pdf' .gitattributes    # Track *.pdf
    - grep -i '^fonts/**' .gitattributes  # Track fonts/**
    - grep -i 'img/small.jpg' lfs-files.txt
    - grep -i 'docs/9711213.pdf' lfs-files.txt
    - grep -i 'fonts/Joan-Regular.ttf' lfs-files.txt
    - git lfs ls-files | grep 'img/small.jpg'
    - git lfs ls-files | grep 'docs/9711213.pdf'
    - git lfs ls-files | grep 'fonts/Joan-Regular.ttf'
